import type { Level } from "../../types/snake-game";

export const LEVELS: Level[] = [
  {
    id: 1,
    name: "Classic Start",
    description: "Just like the old Nokia days",
    gridSize: 15,
    obstacles: [],
    foodTarget: 5,
    speed: 200,
    color: "emerald",
    allowWallWrap: true,
  },
  {
    id: 2,
    name: "Speed Boost",
    description: "A bit faster now",
    gridSize: 15,
    obstacles: [],
    foodTarget: 7,
    speed: 170,
    color: "blue",
    allowWallWrap: true,
  },
  {
    id: 3,
    name: "First Obstacles",
    description: "Watch out for the blocks",
    gridSize: 17,
    obstacles: [
      { x: 8, y: 8 },
      { x: 8, y: 9 },
    ],
    foodTarget: 8,
    speed: 160,
    color: "purple",
    allowWallWrap: true,
  },
  {
    id: 4,
    name: "Corner Trap",
    description: "Obstacles in the corners",
    gridSize: 17,
    obstacles: [
      { x: 2, y: 2 },
      { x: 3, y: 2 },
      { x: 2, y: 3 },
      { x: 14, y: 2 },
      { x: 13, y: 2 },
      { x: 14, y: 3 },
      { x: 2, y: 14 },
      { x: 3, y: 14 },
      { x: 2, y: 13 },
      { x: 14, y: 14 },
      { x: 13, y: 14 },
      { x: 14, y: 13 },
    ],
    foodTarget: 10,
    speed: 150,
    color: "orange",
    allowWallWrap: true,
  },
  {
    id: 5,
    name: "Cross Roads",
    description: "Navigate the crossroads",
    gridSize: 19,
    obstacles: [
      { x: 9, y: 4 },
      { x: 9, y: 5 },
      { x: 9, y: 6 },
      { x: 9, y: 13 },
      { x: 9, y: 14 },
      { x: 9, y: 15 },
      { x: 4, y: 9 },
      { x: 5, y: 9 },
      { x: 6, y: 9 },
      { x: 13, y: 9 },
      { x: 14, y: 9 },
      { x: 15, y: 9 },
    ],
    foodTarget: 12,
    speed: 140,
    color: "red",
    allowWallWrap: true,
  },
  {
    id: 6,
    name: "Speed Demon",
    description: "Fast and furious",
    gridSize: 15,
    obstacles: [],
    foodTarget: 15,
    speed: 120,
    color: "cyan",
    allowWallWrap: true,
  },
  {
    id: 7,
    name: "The Maze",
    description: "Find your way through",
    gridSize: 21,
    obstacles: [
      { x: 5, y: 5 },
      { x: 6, y: 5 },
      { x: 7, y: 5 },
      { x: 8, y: 5 },
      { x: 10, y: 5 },
      { x: 11, y: 5 },
      { x: 12, y: 5 },
      { x: 13, y: 5 },
      { x: 15, y: 5 },
      { x: 16, y: 5 },
      { x: 5, y: 15 },
      { x: 6, y: 15 },
      { x: 7, y: 15 },
      { x: 8, y: 15 },
      { x: 10, y: 15 },
      { x: 11, y: 15 },
      { x: 12, y: 15 },
      { x: 13, y: 15 },
      { x: 15, y: 15 },
      { x: 16, y: 15 },
    ],
    foodTarget: 18,
    speed: 130,
    color: "indigo",
    allowWallWrap: false,
  },
  {
    id: 8,
    name: "Spiral Challenge",
    description: "Follow the spiral path",
    gridSize: 19,
    obstacles: [
      { x: 4, y: 4 },
      { x: 5, y: 4 },
      { x: 6, y: 4 },
      { x: 7, y: 4 },
      { x: 8, y: 4 },
      { x: 9, y: 4 },
      { x: 10, y: 4 },
      { x: 11, y: 4 },
      { x: 12, y: 4 },
      { x: 13, y: 4 },
      { x: 14, y: 4 },
      { x: 14, y: 5 },
      { x: 14, y: 6 },
      { x: 14, y: 7 },
      { x: 14, y: 8 },
      { x: 14, y: 9 },
      { x: 14, y: 10 },
      { x: 14, y: 11 },
      { x: 14, y: 12 },
      { x: 14, y: 13 },
      { x: 14, y: 14 },
      { x: 13, y: 14 },
      { x: 12, y: 14 },
      { x: 11, y: 14 },
      { x: 10, y: 14 },
      { x: 9, y: 14 },
      { x: 8, y: 14 },
      { x: 7, y: 14 },
      { x: 6, y: 14 },
      { x: 6, y: 13 },
      { x: 6, y: 12 },
      { x: 6, y: 11 },
      { x: 6, y: 10 },
      { x: 6, y: 9 },
      { x: 6, y: 8 },
      { x: 6, y: 7 },
      { x: 6, y: 6 },
      { x: 7, y: 6 },
      { x: 8, y: 6 },
      { x: 9, y: 6 },
      { x: 10, y: 6 },
      { x: 11, y: 6 },
      { x: 12, y: 6 },
      { x: 12, y: 7 },
      { x: 12, y: 8 },
      { x: 12, y: 9 },
      { x: 12, y: 10 },
      { x: 12, y: 11 },
      { x: 12, y: 12 },
      { x: 11, y: 12 },
      { x: 10, y: 12 },
      { x: 9, y: 12 },
      { x: 8, y: 12 },
      { x: 8, y: 11 },
      { x: 8, y: 10 },
      { x: 8, y: 9 },
      { x: 8, y: 8 },
      { x: 9, y: 8 },
      { x: 10, y: 8 },
      { x: 10, y: 9 },
      { x: 10, y: 10 },
    ],
    foodTarget: 20,
    speed: 125,
    color: "pink",
    allowWallWrap: false,
  },
  {
    id: 9,
    name: "Lightning Fast",
    description: "Can you keep up?",
    gridSize: 17,
    obstacles: [],
    foodTarget: 20,
    speed: 100,
    color: "yellow",
    allowWallWrap: true,
  },
  {
    id: 10,
    name: "Obstacle Course",
    description: "Navigate through the course",
    gridSize: 21,
    obstacles: [
      { x: 3, y: 3 },
      { x: 4, y: 3 },
      { x: 5, y: 3 },
      { x: 15, y: 3 },
      { x: 16, y: 3 },
      { x: 17, y: 3 },
      { x: 3, y: 17 },
      { x: 4, y: 17 },
      { x: 5, y: 17 },
      { x: 15, y: 17 },
      { x: 16, y: 17 },
      { x: 17, y: 17 },
      { x: 10, y: 7 },
      { x: 10, y: 8 },
      { x: 10, y: 9 },
      { x: 10, y: 11 },
      { x: 10, y: 12 },
      { x: 10, y: 13 },
      { x: 7, y: 10 },
      { x: 8, y: 10 },
      { x: 9, y: 10 },
      { x: 11, y: 10 },
      { x: 12, y: 10 },
      { x: 13, y: 10 },
    ],
    foodTarget: 25,
    speed: 115,
    color: "teal",
    allowWallWrap: false,
  },
  {
    id: 11,
    name: "Classic Nokia",
    description: "Pure Nokia experience",
    gridSize: 19,
    obstacles: [],
    foodTarget: 30,
    speed: 110,
    color: "green",
    allowWallWrap: true,
  },
  {
    id: 12,
    name: "Border Patrol",
    description: "Obstacles around the edges",
    gridSize: 19,
    obstacles: [
      { x: 1, y: 1 },
      { x: 2, y: 1 },
      { x: 3, y: 1 },
      { x: 15, y: 1 },
      { x: 16, y: 1 },
      { x: 17, y: 1 },
      { x: 1, y: 17 },
      { x: 2, y: 17 },
      { x: 3, y: 17 },
      { x: 15, y: 17 },
      { x: 16, y: 17 },
      { x: 17, y: 17 },
      { x: 1, y: 9 },
      { x: 17, y: 9 },
      { x: 9, y: 1 },
      { x: 9, y: 17 },
    ],
    foodTarget: 22,
    speed: 105,
    color: "slate",
    allowWallWrap: false,
  },
  {
    id: 13,
    name: "Speed Master",
    description: "Ultimate speed challenge",
    gridSize: 15,
    obstacles: [],
    foodTarget: 35,
    speed: 80,
    color: "red",
    allowWallWrap: true,
  },
  {
    id: 14,
    name: "The Labyrinth",
    description: "Lost in the maze",
    gridSize: 23,
    obstacles: [
      { x: 2, y: 2 },
      { x: 3, y: 2 },
      { x: 4, y: 2 },
      { x: 6, y: 2 },
      { x: 7, y: 2 },
      { x: 8, y: 2 },
      { x: 10, y: 2 },
      { x: 11, y: 2 },
      { x: 12, y: 2 },
      { x: 14, y: 2 },
      { x: 15, y: 2 },
      { x: 16, y: 2 },
      { x: 18, y: 2 },
      { x: 19, y: 2 },
      { x: 20, y: 2 },
      { x: 2, y: 4 },
      { x: 4, y: 4 },
      { x: 6, y: 4 },
      { x: 8, y: 4 },
      { x: 10, y: 4 },
      { x: 12, y: 4 },
      { x: 14, y: 4 },
      { x: 16, y: 4 },
      { x: 18, y: 4 },
      { x: 20, y: 4 },
      { x: 2, y: 6 },
      { x: 4, y: 6 },
      { x: 6, y: 6 },
      { x: 8, y: 6 },
      { x: 10, y: 6 },
      { x: 12, y: 6 },
      { x: 14, y: 6 },
      { x: 16, y: 6 },
      { x: 18, y: 6 },
      { x: 20, y: 6 },
    ],
    foodTarget: 30,
    speed: 120,
    color: "purple",
    allowWallWrap: false,
  },
  {
    id: 15,
    name: "Insane Speed",
    description: "Only for the brave",
    gridSize: 17,
    obstacles: [],
    foodTarget: 40,
    speed: 60,
    color: "orange",
    allowWallWrap: true,
  },
  {
    id: 16,
    name: "The Fortress",
    description: "Break through the walls",
    gridSize: 21,
    obstacles: [
      { x: 6, y: 6 },
      { x: 7, y: 6 },
      { x: 8, y: 6 },
      { x: 9, y: 6 },
      { x: 10, y: 6 },
      { x: 11, y: 6 },
      { x: 12, y: 6 },
      { x: 13, y: 6 },
      { x: 14, y: 6 },
      { x: 6, y: 14 },
      { x: 7, y: 14 },
      { x: 8, y: 14 },
      { x: 9, y: 14 },
      { x: 10, y: 14 },
      { x: 11, y: 14 },
      { x: 12, y: 14 },
      { x: 13, y: 14 },
      { x: 14, y: 14 },
      { x: 6, y: 7 },
      { x: 6, y: 8 },
      { x: 6, y: 9 },
      { x: 6, y: 10 },
      { x: 6, y: 11 },
      { x: 6, y: 12 },
      { x: 6, y: 13 },
      { x: 14, y: 7 },
      { x: 14, y: 8 },
      { x: 14, y: 9 },
      { x: 14, y: 10 },
      { x: 14, y: 11 },
      { x: 14, y: 12 },
      { x: 14, y: 13 },
    ],
    foodTarget: 28,
    speed: 110,
    color: "gray",
    allowWallWrap: false,
  },
  {
    id: 17,
    name: "Nokia Legend",
    description: "The ultimate Nokia tribute",
    gridSize: 19,
    obstacles: [],
    foodTarget: 50,
    speed: 90,
    color: "green",
    allowWallWrap: true,
  },
  {
    id: 18,
    name: "Chaos Mode",
    description: "Random obstacles everywhere",
    gridSize: 21,
    obstacles: [
      { x: 3, y: 5 },
      { x: 7, y: 3 },
      { x: 11, y: 7 },
      { x: 15, y: 5 },
      { x: 5, y: 11 },
      { x: 9, y: 15 },
      { x: 13, y: 11 },
      { x: 17, y: 13 },
      { x: 5, y: 17 },
      { x: 15, y: 15 },
      { x: 3, y: 13 },
      { x: 7, y: 9 },
      { x: 11, y: 3 },
      { x: 17, y: 7 },
      { x: 9, y: 5 },
      { x: 13, y: 17 },
    ],
    foodTarget: 35,
    speed: 100,
    color: "red",
    allowWallWrap: true,
  },
  {
    id: 19,
    name: "Lightning Strike",
    description: "Fastest speed possible",
    gridSize: 15,
    obstacles: [],
    foodTarget: 45,
    speed: 50,
    color: "yellow",
    allowWallWrap: true,
  },
  {
    id: 20,
    name: "Master of Snake",
    description: "The final challenge",
    gridSize: 25,
    obstacles: [
      { x: 5, y: 5 },
      { x: 6, y: 5 },
      { x: 7, y: 5 },
      { x: 17, y: 5 },
      { x: 18, y: 5 },
      { x: 19, y: 5 },
      { x: 5, y: 19 },
      { x: 6, y: 19 },
      { x: 7, y: 19 },
      { x: 17, y: 19 },
      { x: 18, y: 19 },
      { x: 19, y: 19 },
      { x: 12, y: 8 },
      { x: 12, y: 9 },
      { x: 12, y: 10 },
      { x: 12, y: 14 },
      { x: 12, y: 15 },
      { x: 12, y: 16 },
      { x: 8, y: 12 },
      { x: 9, y: 12 },
      { x: 10, y: 12 },
      { x: 14, y: 12 },
      { x: 15, y: 12 },
      { x: 16, y: 12 },
    ],
    foodTarget: 60,
    speed: 85,
    color: "purple",
    allowWallWrap: false,
  },
];
