// export * from "@/components/ui/button";
export { default as Header } from "./my-uis/Home/Header";
export { default as HeroSection } from "./my-uis/Home/HeroSection";
export { default as MyWorkSection } from "./my-uis/Home/MyWorkSection";
export { default as MyTechStackSection } from "./my-uis/Home/MyTechStackSection";
export { default as Projects } from "./my-uis/Home/Projects";
export { default as Footer } from "./my-uis/Home/Footer";
export { default as AboutMe } from "./my-uis/Home/AboutMe";
export { default as TicTacToe } from "./OnlineTicTacToe/index";
export { ThemeProvider, useThemeProvider } from "./my-uis/Home/ThemeProvider";
